#!/usr/bin/env bash

# BASIC CONFIGURATION DIRECTORIES SETUP
BACKUP_ROOT="$HOME/.dotfiles-backup"
if [ ! -d "$BACKUP_ROOT" ]; then
    mkdir "$BACKUP_ROOT"
    echo -e "===> Created backup directory: $BACKUP_ROOT.\\n"
fi
SOURCE_ROOT=$(pwd -P)
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}



# =========================================================== #
# = 1 = INTITIAL SETUP AND UPDATE OF OS PACKAGE MANAGER ===== #
# =========================================================== #

#  - Homebrew for macOS
#  - APT for Ubuntu/Debian

if [[ "$OSTYPE" == darwin* ]]; then
    echo -e "\033[0;35m===> STEP 1: Installing and updating Homebrew and packages...\033[0m\\n"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    if ! type brew &>/dev/null; then
        echo -e "\033[0;31m===> ERROR: Homebrew is not installed. Aborting.\033[0m"
        exit 1
    fi
    brew upgrade
else # assumes Ubuntu
    echo -e "\033[0;35m===> STEP 1: Updating APT packages...\033[0m\\n"
    if ! type apt &>/dev/null; then
        echo -e "\033[0;31m===> ERROR: APT is not installed. Aborting.\033[0m"
        exit 1
    fi
    sudo apt update
    sudo apt upgrade --allow-downgrades -y
    echo ""
fi
echo -e "\033[0;32m===> STEP 1: Package manager setup and updated successfully.\033[0m"



# =================================================== #
# = 2 = BASIC TOOL INSTALLATION AND ASSET SETUP ===== #
# =================================================== #

echo -e "\\n\033[0;35m===> STEP 2: Installing basic tools and setting up assets...\033[0m"

# ===> 2.1. Installation of basic tools via Homebrew or APT
BASIC_TOOLS="git python3 curl wget gpg xsel xclip"
if [[ "$OSTYPE" == darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 2.1: Installing basic tools via Homebrew...\033[0m\\n"
    brew install $BASIC_TOOLS
else
    echo -e "\033[0;35m=====> STEP 2.1: Installing basic tools via APT...\033[0m\\n"
    sudo apt install $BASIC_TOOLS -y
fi

# Verify tool installation
if ! type git &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Git is not installed. Aborting.\033[0m"
    exit 1
elif ! type python3 &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Python3 is not installed. Aborting.\033[0m"
    exit 1
elif ! type curl &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Curl is not installed. Aborting.\033[0m"
    exit 1
elif ! type wget &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Wget is not installed. Aborting.\033[0m"
    exit 1
elif ! type gpg &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: GPG is not installed. Aborting.\033[0m"
    exit 1
elif ! type xsel &>/dev/null && ! type xclip &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Neither xsel nor xclip is installed. Aborting.\033[0m"
    exit 1
else
    echo -e "\\n\033[0;32m=====> STEP 2.1: Basic tools installed successfully.\033[0m"
fi

# ===> 2.2. Setup of git configuration
echo -e "\033[0;35m=====> STEP 2.2: Setting up Git configuration...\033[0m"

GIT_SRC="$SOURCE_ROOT/git"
GIT_BCK="$BACKUP_ROOT/git"
GIT_DST="$XDG_CONFIG_HOME/git"

# If git config directory exists, back it up
if [ -d "$GIT_DST" ]; then
    if [ ! -L "$GIT_DST" ]; then
        mv "$GIT_DST" "$GIT_BCK" -f
        echo "=====> Moved directory to backup: $GIT_DST -> $GIT_BCK"
    fi
fi

# If symlink does not exist, create it
if [ ! -L "$GIT_DST" ]; then
    ln -s "$GIT_SRC" "$GIT_DST"
    echo "=====> Created symlink (git config): $GIT_DST -> $GIT_SRC"
fi

# Verify config
if [ ! -f "$GIT_DST/personal.gitconfig" ] && []; then
    echo -e "\033[0;31m=====> ERROR: personal.gitconfig not found in $GIT_DST. Aborting.\033[0m"
    exit 1
elif [ ! -f "$GIT_DST/delta.gitconfig" ] && []; then
    echo -e "\033[0;31m=====> ERROR: delta.gitconfig not found in $GIT_DST. Aborting.\033[0m"
    exit 1
fi

# Add git configuration includes for linked config files
git config --global --replace-all include.path ~/.config/git/personal.gitconfig
git config --global --add include.path ~/.config/git/delta.gitconfig

echo -e "\033[0;32m=====> STEP 2.2: Git configuration set up successfully.\033[0m"

# ===> 2.3. Linking to custom scripts directory
echo -e "\033[0;35m=====> STEP 2.3: Setting up link to custom scripts directory...\033[0m"

SCRIPT_SRC="$SOURCE_ROOT/assets/scripts"
SCRIPT_BCK="$BACKUP_ROOT/scripts"
SCRIPT_DST="$HOME/.scripts"

# If scripts directory exists, back it up
if [ -d "$SCRIPT_DST" ]; then
    if [ ! -L "$SCRIPT_DST" ]; then
        mv "$SCRIPT_DST" "$SCRIPT_BCK" -f
        echo "=====> Moved directory to backup: $SCRIPT_DST -> $SCRIPT_BCK"
    fi
fi

# If symlink does not exist, create it
if [ ! -L "$SCRIPT_DST" ]; then
    ln -s "$SCRIPT_SRC" "$SCRIPT_DST"
    echo "=====> Created symlink (custom scripts): $SCRIPT_DST -> $SCRIPT_SRC"
fi

echo -e "\033[0;32m=====> STEP 2.3: Custom scripts directory linked successfully.\033[0m"

# ===> 2.4. Import and add required fonts (Meslo Nerd Font)
echo -e "\033[0;35m=====> STEP 2.4: Installing required fonts...\033[0m\\n"

# Determine target font directory based on OS type
if [[ "$OSTYPE" == darwin* ]]; then
    TARGET_FONT_DIR=$HOME/Library/fonts
else
    TARGET_FONT_DIR=$HOME/.fonts
fi

# Assure that target font directory exists
if [[ ! -d TARGET_FONT_DIR ]]; then
    mkdir -p "$TARGET_FONT_DIR"
fi

# Font - MesloLGS NF (sourced from powerlevel10k-media repository)
P10KM_REPO_DIR=$XDG_CONFIG_HOME/.temp/powerlevel10k-media
if [[ -d P10KM_REPO_DIR ]]; then
    rm -rf "$P10KM_REPO_DIR"
fi
git clone --depth 1 https://github.com/romkatv/powerlevel10k-media $P10KM_REPO_DIR
yes | cp "$P10KM_REPO_DIR"/*.ttf "$TARGET_FONT_DIR/"

# Remove temporary repository directory, refresh font cache, and verify installation
rm -rf "$P10KM_REPO_DIR"
echo -e "\\n=====> Updating font cache..."
fc-cache -f
if [ "$(fc-list | grep -c 'MesloLGS NF')" != "4" ]; then
    echo -e "\033[0;31m=====> ERROR: Font installation failed. Aborting.\033[0m"
    exit 1
else
    echo -e "\\n\033[0;32m=====> STEP 2.4: Fonts installed successfully.\033[0m"
fi

# ===> 2.5. (Ubuntu-only) Add wallpaper for i3 desktop (based on given argument)
if [[ "$OSTYPE" != darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 2.5: Setting up wallpaper...\033[0m"

    IMG_SRC_BASE="$SOURCE_ROOT/assets/wallpapers"
    IMG_DST_BASE="$HOME/Pictures"
    IMG_DST="$IMG_DST_BASE/wallpaper.jpg"

    # Establish specific wallpaper file based on the system name
    COMP_NAME=$(uname -n | tr '[:upper:]' '[:lower:]')
    if [[ "$COMP_NAME" =~ "vx" || "$COMP_NAME" =~ "vortex" ]]; then
        IMG_SRC="$IMG_SRC_BASE/vortex.jpg"
    else
        # TODO: Add default wallpaper
        IMG_SRC="$IMG_SRC_BASE/vortex.jpg"
    fi

    # Assure that local directory for wallpapers exists
    if [ ! -d "$IMG_DST_BASE" ]; then
        mkdir -p "$IMG_DST_BASE"
    fi

    # Copy the wallpaper image to the destination
    yes | cp "$IMG_SRC" "$IMG_DST"
    echo "=====> Copied wallpaper: $IMG_SRC -> $IMG_DST"

    # Verify if the wallpaper was copied successfully
    if [ ! -f "$IMG_DST" ]; then
        echo -e "\033[0;31m=====> ERROR: Wallpaper copy failed. Aborting.\033[0m"
        exit 1
    else
        echo -e "\033[0;32m=====> STEP 2.5: Wallpaper set up successfully.\033[0m"
    fi
fi

echo -e "\033[0;32m===> STEP 2: Basic tools and assets set up successfully.\033[0m"



# ================================ #
# = 3 = WINDOW MANAGER SETUP ===== #
# ================================ #

if [[ "$OSTYPE" == darwin* ]]; then
    echo -e "\\n\033[0;35m===> STEP 3: Installing and configuring window manager... Skipped for MacOS.\033[0m\\n"
else
    echo -e "\\n\033[0;35m===> STEP 3: Installing and configuring window manager...\033[0m"

    # ===> 3.1. Installation of window manager and related tools via APT
    echo -e "\033[0;35m=====> STEP 3.1: Installing i3 and related tools via APT...\033[0m\\n"
    WM_TOOLS="i3 i3lock xautolock feh picom"
    sudo apt install $WM_TOOLS -y

    # Verify tool installation
    if ! type i3 &>/dev/null; then
        echo -e "\\n\033[0;31m=====> ERROR: i3 Window Manager is not installed. Aborting.\033[0m"
        exit 1
    elif ! type i3lock &>/dev/null; then
        echo -e "\\n\033[0;31m=====> ERROR: i3 Lock is not installed. Aborting.\033[0m"
        exit 1
    elif ! type xautolock &>/dev/null; then
        echo -e "\\n\033[0;31m=====> ERROR: Xautolock is not installed. Aborting.\033[0m"
        exit 1
    elif ! type feh &>/dev/null; then
        echo -e "\\n\033[0;31m=====> ERROR: Feh is not installed. Aborting.\033[0m"
        exit 1
    elif ! type picom &>/dev/null; then
        echo -e "\\n\033[0;31m=====> ERROR: Picom is not installed. Aborting.\033[0m"
        exit 1
    else
        echo -e "\\n\033[0;32m=====> STEP 3.1: i3 and related tools installed successfully.\033[0m"
    fi

    # ===> 3.2. Installation of bumblebee (status bar for i3) via PIP
    echo -e "\033[0;35m=====> STEP 3.2: Installing bumblebee (status bar for i3) via PIP...\033[0m\\n"
    pip install --user psutil bumblebee-status

    # Verify installation
    if ! type bumblebee-status &>/dev/null; then
        echo -e "\\n\033[0;31m=====> ERROR: Bumblebee Status Bar is not installed. Aborting.\033[0m"
        exit 1
    else
        echo -e "\\n\033[0;32m=====> STEP 3.2: Bumblebee (status bar for i3) installed successfully.\033[0m"
    fi

    # ===> 3.3. Setup of i3 configuration
    echo -e "\033[0;35m=====> STEP 3.3: Setting up i3 configuration...\033[0m"

    I3_SRC="$SOURCE_ROOT/i3"
    I3_BCK="$BACKUP_ROOT/i3"
    I3_DST="$XDG_CONFIG_HOME/i3"

    # If i3 config directory exists, back it up
    if [ -d "$I3_DST" ]; then
        if [ ! -L "$I3_DST" ]; then
            mv "$I3_DST" "$I3_BCK" -f
            echo "=====> Moved directory to backup: $I3_DST -> $I3_BCK"
        fi
    fi

    # If symlink does not exist, create it
    if [ ! -L "$I3_DST" ]; then
        ln -s "$I3_SRC" "$I3_DST"
        echo "=====> Created symlink (i3 config): $I3_DST -> $I3_SRC"
    fi

    echo -e "\033[0;32m=====> STEP 3.3: i3 configuration set up successfully.\033[0m"

    # ===> 3.4. Setup of Picom configuration
    echo -e "\033[0;35m=====> STEP 3.4: Setting up Picom configuration...\033[0m"

    PICOM_SRC="$SRC_ROOT/picom"
    PICOM_BCK="$BCK_ROOT/picom"
    PICOM_DST="$XDG_CONFIG_HOME/picom"

    if [ -d "$PICOM_DST" ]; then
        if [ ! -L "$PICOM_DST" ]; then
            mv "$PICOM_DST" "$PICOM_BCK" -f
            echo "=====> Moved directory to backup: $PICOM_DST -> $PICOM_BCK"
        fi
    fi

    if [ ! -L "$PICOM_DST" ]; then
        ln -s "$PICOM_SRC" "$PICOM_DST"
        echo "Created symlink (Picom config): $PICOM_DST -> $PICOM_SRC"
    fi

    echo -e "\033[0;32m=====> STEP 3.4: Picom configuration set up successfully.\033[0m"

    echo -e "\033[0;32m===> STEP 3: Window manager (i3) installed and set up successfully.\033[0m"
fi



# =================================== #
# = 4 = TERMINAL EMULATOR SETUP ===== #
# =================================== #

echo -e "\\n\033[0;35m===> STEP 4: Setting up Kitty terminal...\033[0m"

# ===> 4.1. Installation of Kitty terminal via APT
if [[ "$OSTYPE" == darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 4.1: Installing Kitty terminal via Homebrew...\033[0m\\n"
    brew install kitty
else
    echo -e "\033[0;35m=====> STEP 4.1: Installing Kitty terminal via APT...\033[0m\\n"
    sudo apt install kitty -y
fi

# Verify installation
if ! type kitty &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Kitty terminal is not installed. Aborting.\033[0m"
    exit 1
else
    echo -e "\\n\033[0;32m=====> STEP 4.1: Kitty terminal installed successfully.\033[0m"
fi

# ===> 4.2. Setup of Kitty configuration
echo -e "\033[0;35m=====> STEP 4.2: Setting up Kitty configuration...\033[0m"

KITTY_SRC="$SOURCE_ROOT/kitty"
KITTY_BCK="$BACKUP_ROOT/kitty"
KITTY_DST="$XDG_CONFIG_HOME/kitty"

# If Kitty config directory exists, back it up
if [ -d "$KITTY_DST" ]; then
  if [ ! -L "$KITTY_DST" ]; then
    mv "$KITTY_DST" "$KITTY_BCK"
    echo "=====> Moved file to backup: $KITTY_DST -> $KITTY_BCK"
  fi
fi

# If symlink does not exist, create it
if [ ! -L "$KITTY_DST" ]; then
  ln -s "$KITTY_SRC" "$KITTY_DST"
  echo "=====> Created symlink (kitty config): $KITTY_DST -> $KITTY_SRC"
fi

echo -e "\033[0;32m=====> STEP 4.2: Kitty configuration set up successfully.\033[0m"



# ====================================== #
# = 5 = TERMINAL MULTIPLEXER SETUP ===== #
# ====================================== #

echo -e "\\n\033[0;35m===> STEP 5: Setting up terminal multiplexer (tmux)...\033[0m"

# ===> 5.1. Installation of tmux via APT or Homebrew
if [[ "$OSTYPE" == darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 5.1: Installing tmux via Homebrew...\033[0m\\n"
    brew install tmux
else
    echo -e "\033[0;35m=====> STEP 5.1: Installing tmux via APT...\033[0m\\n"
    sudo apt install tmux -y
fi

# Verify installation
if ! type tmux &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Tmux is not installed. Aborting.\033[0m"
    exit 1
else
    echo -e "\\n\033[0;32m=====> STEP 5.1: Tmux installed successfully.\033[0m"
fi

# ===> 5.2. Setup of Tmux configuration
echo -e "\033[0;35m=====> STEP 5.2: Setting up Tmux configuration...\033[0m"

TMUX_SRC="$SOURCE_ROOT/tmux"
TMUX_BCK="$BACKUP_ROOT/tmux"
TMUX_DST="$XDG_CONFIG_HOME/tmux"

# If Tmux config directory exists, back it up
if [ -d "$TMUX_DST" ]; then
  if [ ! -L "$TMUX_DST" ]; then
    mv "$TMUX_DST" "$TMUX_BCK" -f
    echo "=====> Moved directory to backup: $TMUX_DST -> $TMUX_BCK"
  fi
fi

# If symlink does not exist, create it
if [ ! -L "$TMUX_DST" ]; then
  ln -s "$TMUX_SRC" "$TMUX_DST"
  echo "=====> Created symlink (tmux config): $TMUX_DST -> $TMUX_SRC"
fi

echo -e "\033[0;32m=====> STEP 4.2: Tmux configuration set up successfully.\033[0m"

# ===> 5.3. Installation and uptdate of Tmux Plugin Manager (TPM)
echo -e "\033[0;35m=====> STEP 5.3: Installing and updating Tmux Plugin Manager (TPM)...\033[0m\\n"

# Clone TPM repo if it does not exist, otherwise pull changes
TPM_DST="$HOME/.tmux/plugins/tpm"
if [ ! -d "$TPM_DST" ]; then
    git clone https://github.com/tmux-plugins/tpm "$TPM_DST"
else
    cd "$TPM_DST" && git pull && cd $SOURCE_ROOT
fi

# Execute TPM to install plugins
"$TPM_DST/tpm"

# Verify TPM installation
if [ $? -ne 0 ]; then
    echo -e "\\n\033[0;31m=====> ERROR: Tmux Plugin Manager (TPM) installation failed. Aborting.\033[0m"
    exit 1
fi

echo -e "\\n\033[0;32m=====> STEP 5.3: Tmux Plugin Manager (TPM) installed and updated successfully.\033[0m"

echo -e "\033[0;32m===> STEP 5: Terminal multiplexer (tmux) set up successfully.\033[0m"



# ======================= #
# = 6 = SETUP SHELL ===== #
# ======================= #

echo -e "\\n\033[0;35m===> STEP 6: Setting up shell (zsh)...\033[0m"

# ===> 6.1. Installation of zsh and related packages via APT or Homebrew
if [[ "$OSTYPE" == darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 6.1: Installing zsh and related packages via Homebrew...\033[0m\\n"
    brew install zsh zsh-autosuggestions zsh-completions
else
    echo -e "\033[0;35m=====> STEP 6.1: Installing zsh and related packages via APT...\033[0m\\n"
    sudo apt install zsh zsh-autosuggestions -y
fi

# Verify installation
if ! type zsh &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Zsh is not installed. Aborting.\033[0m"
    exit 1
else
    echo -e "\\n\033[0;32m=====> STEP 6.1: Zsh and related packages installed successfully.\033[0m"
fi

# ===> 6.2. Setup of Zsh configuration
echo -e "\033[0;35m=====> STEP 6.2: Setting up Zsh configuration...\033[0m"

ZSHRC_SRC="$SOURCE_ROOT/zsh/.zshrc"
ZSHRC_BCK="$BACKUP_ROOT/zsh/.zshrc"
ZSHRC_DST="$HOME/.zshrc"

# If Zsh config file exists, back it up
if [ -f "$ZSHRC_DST" ]; then
  if [ ! -L "$ZSHRC_DST" ]; then
    mkdir -p "$BCK_ROOT/zsh"
    mv "$ZSHRC_DST" "$ZSHRC_BCK" -f
    echo "=====> Moved file to backup: $ZSHRC_DST -> $ZSHRC_BCK"
  fi
fi

# If symlink does not exist, create it
if [ ! -L "$ZSHRC_DST" ]; then
  ln -s "$ZSHRC_SRC" "$ZSHRC_DST"
  echo "===== >Created symlink (zsh config file): $ZSHRC_DST -> $ZSHRC_SRC"
fi

ZSH_SRC="$SOURCE_ROOT/zsh"
ZSH_BCK="$BACKUP_ROOT/zsh"
ZSH_DST="$XDG_CONFIG_HOME/zsh"

# If Zsh config directory exists, back it up
if [ -d "$ZSH_DST" ]; then
  if [ ! -L "$ZSH_DST" ]; then
    mv "$ZSH_DST" "$ZSH_BCK" -f
    echo "=====> Moved directory to backup: $ZSH_DST -> $ZSH_BCK"
  fi
fi

# If symlink does not exist, create it
if [ ! -L "$ZSH_DST" ]; then
  ln -s "$ZSH_SRC" "$ZSH_DST"
  echo "=====> Created symlink (zsh config directory): $ZSH_DST -> $ZSH_SRC"
fi

echo -e "\033[0;32m=====> STEP 6.2: Zsh configuration set up successfully.\033[0m"

# ===> 6.3. Set Zsh as the default shell
echo -e "\033[0;35m=====> STEP 6.3: Setting Zsh as the default shell...\033[0m"

# Add Zsh to the list of allowed shells if not already present
if ! grep -q "$(which zsh)" /etc/shells; then
    echo "$(which zsh)" | sudo tee -a /etc/shells > /dev/null
fi

if [ "$SHELL" != "$(which zsh)" ]; then
    chsh -s "$(which zsh)"
    echo "=====> Changed default shell to Zsh."
    sudo chsh -s "$(which zsh)"
    echo "=====> Changed root shell to Zsh."
else
    echo "=====> Zsh is already the default shell."
fi

echo -e "\033[0;32m=====> STEP 6.3: Zsh set as the default shell successfully.\033[0m"

# ===> 6.4. Fix permissions for Homebrew-installed zsh-completions (MacoOS-only)
if [[ "$OSTYPE" == darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 6.4: Fixing permissions for zsh-completions...\033[0m"
    chmod go-w '/opt/homebrew/share'
    chmod -R go-w '/opt/homebrew/share/zsh'
    echo -e "\033[0;32m=====> STEP 6.4: Permissions for zsh-completions fixed successfully.\033[0m"
else
    echo -e "\033[0;35m=====> STEP 6.4: Skipped for non-MacOS systems.\033[0m"
fi

echo -e "\033[0;32m===> STEP 6: Shell (zsh) set up successfully.\033[0m"



# =================================== #
# = 7 = INSTALL EXTRA CLI TOOLS ===== #
# =================================== #

echo -e "\\n\033[0;35m===> STEP 7: Installing extra CLI tools...\033[0m"

# ===> 7.1. Installation of extra CLI tools via Homebrew or APT
if [[ "$OSTYPE" == darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 7.1: Installing extra CLI tools via Homebrew...\033[0m\\n"
    brew install bat ripgrep gh tealdeer eza git-delta
    BAT_CMD_NAME=bat
else
    echo -e "\033[0;35m=====> STEP 7.1: Installing extra CLI tools via APT...\033[0m\\n"
    sudo apt install bat ripgrep gh tldr -y
    BAT_CMD_NAME=batcat
fi

# Verify tool installation
if ! type "$BAT_CMD_NAME" &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Bat is not installed. Aborting.\033[0m"
    exit 1
elif ! type rg &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Ripgrep is not installed. Aborting.\033[0m"
    exit 1
elif ! type gh &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: GitHub CLI is not installed. Aborting.\033[0m"
    exit 1
elif ! type tldr &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Tealdeer is not installed. Aborting.\033[0m"
    exit 1
elif ! type eza &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Eza is not installed. Aborting.\033[0m"
    exit 1
elif ! type delta &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: Git Delta is not installed. Aborting.\033[0m"
    exit 1
else
    echo -e "\\n\033[0;32m=====> STEP 7.1: Extra CLI tools installed successfully.\033[0m"
fi

# ===> 7.2. Update Tldr pages cache
echo -e "\033[0;35m=====> STEP 7.2: Updating Tldr pages cache...\033[0m"
tldr --update
if [ $? -ne 0 ]; then
    echo -e "\033[0;31m=====> ERROR: Tldr pages update failed. Aborting.\033[0m"
    exit 1
else
    echo -e "\033[0;32m=====> STEP 7.2: Tldr pages cache updated successfully.\033[0m"
fi

# ===> 7.3. Manual install of FZF
echo -e "\033[0;35m=====> STEP 7.3: Installing FZF (Fuzzy Finder)...\033[0m\\n"

# Determine and clear directory to clone FZF repo
FZF_REPO_DIR=$XDG_CONFIG_HOME/.temp/fzf
if [[ -d FZF_REPO_DIR ]]; then
    rm -rf "$FZF_REPO_DIR"
fi

git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_REPO_DIR
"$FZF_REPO_DIR/install" --xdg --key-bindings --completion --no-update-rc
rm -rf "$FZF_REPO_DIR"

# Verify FZF installation
if ! type fzf &>/dev/null; then
    echo -e "\\n\033[0;31m=====> ERROR: FZF is not installed. Aborting.\033[0m"
    exit 1
else
    echo -e "\\n\033[0;32m=====> STEP 7.3: FZF installed successfully.\033[0m"
fi

# ===> 7.4. Manual install of Git Delta (Ubuntu only)
if [[ "$OSTYPE" != darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 7.4: Installing Git Delta...\033[0m\\n"

    GIT_DELTA_FILENAME=git-delta_0.18.2_amd64.deb
    wget https://github.com/dandavison/delta/releases/download/0.18.2/$GIT_DELTA_FILENAME
    sudo dpkg -i $GIT_DELTA_FILENAME
    rm $GIT_DELTA_FILENAME

    # Verify Git Delta installation
    if ! type delta &>/dev/null; then
        echo -e "\\n\033[0;31m=====> ERROR: Git Delta is not installed. Aborting.\033[0m"
        exit 1
    else
        echo -e "\\n\033[0;32m=====> STEP 7.4: Git Delta installed successfully.\033[0m"
    fi
fi

# ===> 7.5. Manual install of Eza (Ubuntu only)
if [[ "$OSTYPE" != darwin* ]]; then
    echo -e "\033[0;35m=====> STEP 7.5: Installing Eza (replacement for ls)...\033[0m\\n"

    # Add Gierens repository for Eza
    sudo mkdir -p /etc/apt/keyrings
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
    sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    sudo apt update

    # Install Eza via APT
    sudo apt install eza -y

    # Verify Eza installation
    if ! type eza &>/dev/null; then
        echo -e "\\n\033[0;31m=====> ERROR: Eza is not installed. Aborting.\033[0m"
        exit 1
    else
        echo -e "\\n\033[0;32m=====> STEP 7.5: Eza installed successfully.\033[0m"
    fi
fi

echo -e "\033[0;32m===> STEP 7: Extra CLI tools installed successfully.\033[0m"
