#!/usr/bin/env bash

sudo apt update
sudo apt upgrade -y

sudo apt install i3 i3lock xautolock feh picom python3 kitty -y
sudo apt install git gpg xclip xsel curl -y
sudo apt install tmux zsh zsh-autosuggestions -y
sudo apt install bat ripgrep gh tldr -y

pip install --user bumblebee-status

# update tldr cache
tldr --update

# install Meslo nerd font from powerlevel10k-media repository
if [[ "$OSTYPE" == darwin* ]]; then
    TARGET_FONT_DIR=$HOME/Library/fonts
else
    TARGET_FONT_DIR=$HOME/.fonts
fi

P10KM_REPO_DIR=$HOME/.config/.temp/powerlevel10k-media
if [[ -d P10KM_REPO_DIR ]]; then
    rm $P10KM_REPO_DIR -rf
fi
if [[ ! -d TARGET_FONT_DIR ]]; then
    mkdir $TARGET_FONT_DIR
fi
git clone --depth 1 https://github.com/romkatv/powerlevel10k-media $P10KM_REPO_DIR;
yes | cp $P10KM_REPO_DIR/*.ttf $TARGET_FONT_DIR/
rm $P10KM_REPO_DIR -rf

# refresh font cache
fc-cache -f

# manual install of fzf
FZF_SRC_DIR=$HOME/.config/fzf/.src
if [[ ! -d FZF_SRC_DIR ]]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_SRC_DIR;
    $FZF_SRC_DIR/install --xdg --key-bindings --completion --no-update-rc;
fi

# manual install of git-delta via dpkg
GIT_DELTA_FILENAME=git-delta_0.18.2_amd64.deb
wget https://github.com/dandavison/delta/releases/download/0.18.2/$GIT_DELTA_FILENAME
sudo dpkg -i $GIT_DELTA_FILENAME
rm $GIT_DELTA_FILENAME

# manual install of eza via apt
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza

# manual clone of tpm (plugin manager for tmux) - and execute it initially
if [ ! -d $HOME/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi
$HOME/.tmux/plugins/tpm/tpm

# change default shell for root and current user
sudo chsh -s $(which zsh)
chsh -s $(which zsh)
