#!/usr/bin/env zsh

brew install python3
brew install font-fontawesome
# brew install fonts-powerline - install via clone
brew install kitty
brew install git gpg wget
brew install xclip xsel
brew install tmux
brew install zsh zsh-autosuggestions
brew install bat ripgrep gh git-delta eza

# manual install of powerline fonts
FONTPL_SRC_DIR=$HOME/.config/font-powerline/.src
if [[ ! -d $FONTPL_SRC_DIR ]]; then
    git clone --depth 1 https://github.com/powerline/fonts.git $FONTPL_SRC_DIR;
    $FONTPL_SRC_DIR/install.sh;
fi

# manual install of fzf
# TODO - what about XDG_... (check)
FZF_SRC_DIR=$HOME/.config/fzf/.src
if [[ ! -d FZF_SRC_DIR ]]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_SRC_DIR;
    $FZF_SRC_DIR/install --xdg --key-bindings --completion --no-update-rc;
fi

# manual clone of tpm (plugin manager for tmux)
if [ ! -d $HOME/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

# refresh font cache
fc-cache -f
