#!/usr/bin/env zsh

brew install python3
brew install kitty
brew install git gpg wget
brew install xclip xsel
brew install tmux
brew install zsh zsh-autosuggestions
brew install bat ripgrep gh git-delta eza

# install Meslo nerd font from powerlevel10k-media repository
if [[ "$OSTYPE" == darwin* ]]; then
    TARGET_FONT_DIR=$HOME/Library/fonts
else
    TARGET_FONT_DIR=$HOME/.fonts
fi

P10KM_REPO_DIR=$HOME/.config/.temp/powerlevel10k-media
if [[ -d P10KM_REPO_DIR ]]; then
    rm -rf $P10KM_REPO_DIR
fi
if [[ ! -d TARGET_FONT_DIR ]]; then
    mkdir $TARGET_FONT_DIR
fi
git clone --depth 1 https://github.com/romkatv/powerlevel10k-media $P10KM_REPO_DIR;
yes | cp $P10KM_REPO_DIR/*.ttf $TARGET_FONT_DIR/
rm -rf $P10KM_REPO_DIR

# refresh font cache
fc-cache -f

# manual install of fzf
# TODO - what about XDG_... (check)
FZF_SRC_DIR=$HOME/.config/fzf/.src
if [[ ! -d FZF_SRC_DIR ]]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_SRC_DIR;
    $FZF_SRC_DIR/install --xdg --key-bindings --completion --no-update-rc;
fi

# manual clone of tpm (plugin manager for tmux)
if [ ! -d $HOME/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi
$HOME/.tmux/plugins/tpm/tpm

